In [1]:
!pip install numpy

In [2]:
!pip install matplotlib
import matplotlib
import numpy as np

In [3]:
array1=np.array([[10,20],[30,40]])
array1

array([[10, 20],
       [30, 40]])

In [4]:
np.square(array1)

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [5]:
array2=array1+100
array2

array([[110, 120],
       [130, 140]])

In [6]:
array3=array1*5
array3

array([[ 50, 100],
       [150, 200]])

In [7]:
np.sqrt(array1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [8]:
x=np.arange(3,30,3).reshape(3,3)
x

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [9]:
y=np.linspace(10,20,9).reshape(3,3)
y

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [10]:
z=x*y
z

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

In [11]:
a=np.load('process1.npy')
a

array([[52, 12, 81,  0, 58]])

In [12]:
b=np.load('process2.npy')
b

array([[96,  4, 61, 16, 43]])

In [13]:
c=np.load('process3.npy')
c

array([[38, 96, 45, 17, 58]])

In [14]:
d=np.load('process4.npy')
d

array([[97, 21, 22, 25,  6]])

In [15]:
e=np.load('process5.npy')
e

array([[77,  6, 19,  2, 74]])

In [16]:
array4=np.vstack([a,b,c,d,e,])
array4

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [17]:
array4.mean(axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])

# Individual NumPy Assignment 2
## Braden Heuglin
### Version 1
#### Spring 2023